import * as schema from '../../db/schema';
import { DocumentRegistry, type DocumentTypeConfig } from './DocumentRegistry';
import { salesDeliveryNoteHooks } from './hooks/salesDeliveryNote';
import { purchaseDeliveryNoteHooks } from './hooks/purchaseDeliveryNote';
import { salesInvoiceHooks } from './hooks/salesInvoice';
import { purchaseInvoiceHooks } from './hooks/purchaseInvoice';

/**
 * Configuraciones de los 6 tipos de documento del sistema.
 * Se registran al importar este módulo.
 */

const CONFIGS: DocumentTypeConfig[] = [
  {
    docType: 'SINV',
    side: 'sales',
    category: 'invoice',
    label: 'Factura de Venta',
    labelPlural: 'Facturas de Venta',
    tableName: 'salesInvoices',
    schemaTable: schema.salesInvoices,
    lineSchemaTable: schema.salesInvoiceLines,
    batchSchemaTable: schema.salesInvoiceLineBatches,
    eventPrefix: 'salesInvoice',
    stockAction: 'OUT',
    closeBaseDocuments: true,
    hooks: salesInvoiceHooks,
    initialStatus: 'D',
    headerPgName: 'SalesInvoice',
    linePgName: 'SalesInvoiceLine',
    lineFk: 'invoiceId',
    headerRefKey: 'invoiceId',
    apiPath: '/api/sales/invoices',
    hasFiscalFields: true,
    hasWarehouse: true,
    hasInternalOrder: false,
    hasSalesAgent: true,
    statusLabels: { O: 'Emitida', C: 'Cerrada', X: 'Cancelada', D: 'Borrador' },
    baseDocType: 'SDN',
  },
  {
    docType: 'PINV',
    side: 'purchase',
    category: 'invoice',
    label: 'Factura de Compra',
    labelPlural: 'Facturas de Compra',
    tableName: 'purchaseInvoices',
    schemaTable: schema.purchaseInvoices,
    lineSchemaTable: schema.purchaseInvoiceLines,
    batchSchemaTable: schema.purchaseInvoiceLineBatches,
    eventPrefix: 'purchaseInvoice',
    stockAction: 'IN',
    closeBaseDocuments: true,
    hooks: purchaseInvoiceHooks,
    initialStatus: 'D',
    headerPgName: 'PurchaseInvoice',
    linePgName: 'PurchaseInvoiceLine',
    lineFk: 'invoiceId',
    headerRefKey: 'invoiceId',
    apiPath: '/api/purchases/invoices',
    hasFiscalFields: true,
    hasWarehouse: true,
    hasInternalOrder: false,
    hasSalesAgent: false,
    statusLabels: { O: 'Registrada', C: 'Cerrada', X: 'Cancelada', D: 'Borrador' },
    baseDocType: 'PDN',
  },
  {
    docType: 'SO',
    side: 'sales',
    category: 'order',
    label: 'Pedido de Venta',
    labelPlural: 'Pedidos de Venta',
    tableName: 'salesOrders',
    schemaTable: schema.salesOrders,
    lineSchemaTable: schema.salesOrderLines,
    batchSchemaTable: null,
    eventPrefix: 'salesOrder',
    stockAction: 'NONE',
    closeBaseDocuments: false,
    initialStatus: 'O',
    headerPgName: 'SalesOrder',
    linePgName: 'SalesOrderLine',
    lineFk: 'orderId',
    headerRefKey: 'orderId',
    apiPath: '/api/sales',
    hasFiscalFields: false,
    hasWarehouse: true,
    hasInternalOrder: true,
    hasSalesAgent: false,
    statusLabels: { O: 'Abierto', P: 'Parcial', C: 'Cerrado', X: 'Cancelado' },
  },
  {
    docType: 'PO',
    side: 'purchase',
    category: 'order',
    label: 'Pedido de Compra',
    labelPlural: 'Pedidos de Compra',
    tableName: 'purchaseOrders',
    schemaTable: schema.purchaseOrders,
    lineSchemaTable: schema.purchaseOrderLines,
    batchSchemaTable: null,
    eventPrefix: 'purchaseOrder',
    stockAction: 'NONE',
    closeBaseDocuments: false,
    initialStatus: 'O',
    headerPgName: 'PurchaseOrder',
    linePgName: 'PurchaseOrderLine',
    lineFk: 'orderId',
    headerRefKey: 'orderId',
    apiPath: '/api/purchases/orders',
    hasFiscalFields: false,
    hasWarehouse: true,
    hasInternalOrder: true,
    hasSalesAgent: false,
    statusLabels: { O: 'Abierto', P: 'Parcial', C: 'Cerrado', X: 'Cancelado' },
  },
  {
    docType: 'SDN',
    side: 'sales',
    category: 'delivery_note',
    label: 'Albarán de Venta',
    labelPlural: 'Albaranes de Venta',
    tableName: 'salesDeliveryNotes',
    schemaTable: schema.salesDeliveryNotes,
    lineSchemaTable: schema.salesDeliveryNoteLines,
    batchSchemaTable: schema.salesDeliveryNoteLineBatches,
    eventPrefix: 'salesDeliveryNote',
    stockAction: 'OUT',
    closeBaseDocuments: false,
    hooks: salesDeliveryNoteHooks,
    initialStatus: 'O',
    headerPgName: 'SalesDeliveryNote',
    linePgName: 'SalesDeliveryNoteLine',
    lineFk: 'deliveryId',
    headerRefKey: 'deliveryId',
    apiPath: '/api/sales/delivery-notes',
    hasFiscalFields: false,
    hasWarehouse: true,
    hasInternalOrder: false,
    hasSalesAgent: false,
    statusLabels: { O: 'Abierto', P: 'Parcial', C: 'Cerrado', X: 'Cancelado' },
  },
  {
    docType: 'PDN',
    side: 'purchase',
    category: 'delivery_note',
    label: 'Albarán de Compra',
    labelPlural: 'Albaranes de Compra',
    tableName: 'purchaseDeliveryNotes',
    schemaTable: schema.purchaseDeliveryNotes,
    lineSchemaTable: schema.purchaseDeliveryNoteLines,
    batchSchemaTable: schema.purchaseDeliveryNoteLineBatches,
    eventPrefix: 'purchaseDeliveryNote',
    stockAction: 'IN',
    closeBaseDocuments: false,
    hooks: purchaseDeliveryNoteHooks,
    initialStatus: 'O',
    headerPgName: 'PurchaseDeliveryNote',
    linePgName: 'PurchaseDeliveryNoteLine',
    lineFk: 'deliveryId',
    headerRefKey: 'deliveryId',
    apiPath: '/api/purchases/delivery-notes',
    hasFiscalFields: false,
    hasWarehouse: true,
    hasInternalOrder: false,
    hasSalesAgent: false,
    statusLabels: { O: 'Abierto', P: 'Parcial', C: 'Cerrado', X: 'Cancelado' },
  },
];

// Registrar todos al importar
for (const config of CONFIGS) {
  DocumentRegistry.register(config);
}

export { CONFIGS };
