import * as schema from '../../db/schema';
import { registerDocTypeMeta } from '@openfactu/common';
import { DocumentRegistry, type DocumentTypeConfig } from './DocumentRegistry';
import { salesDeliveryNoteHooks } from './hooks/salesDeliveryNote';
import { purchaseDeliveryNoteHooks } from './hooks/purchaseDeliveryNote';
import { salesInvoiceHooks } from './hooks/salesInvoice';
import { purchaseInvoiceHooks } from './hooks/purchaseInvoice';
import { salesOrderHooks } from './hooks/salesOrder';

/**
 * Configuraciones de los 6 tipos de documento del sistema.
 * Se registran al importar este módulo.
 */

const CONFIGS: DocumentTypeConfig[] = [
  {
    docType: 'SINV',
    side: 'sales',
    category: 'invoice',
    label: 'Factura de Venta',
    labelPlural: 'Facturas de Venta',
    tableName: 'salesInvoices',
    schemaTable: schema.salesInvoices,
    lineSchemaTable: schema.salesInvoiceLines,
    batchSchemaTable: schema.salesInvoiceLineBatches,
    eventPrefix: 'salesInvoice',
    stockAction: 'OUT',
    closeBaseDocuments: true,
    hooks: salesInvoiceHooks,
    initialStatus: 'D',
    headerPgName: 'SalesInvoice',
    linePgName: 'SalesInvoiceLine',
    lineFk: 'invoiceId',
    headerRefKey: 'invoiceId',
    apiPath: '/api/sales/invoices',
    hasFiscalFields: true,
    hasWarehouse: true,
    hasInternalOrder: false,
    hasSalesAgent: true,
    statusLabels: { O: 'Emitida', C: 'Cerrada', X: 'Cancelada', D: 'Borrador' },
    baseDocType: 'SDN',
    uiRoute: '/sales/invoices',
    linesCarryBaseRef: true,
  },
  {
    docType: 'PINV',
    side: 'purchase',
    category: 'invoice',
    label: 'Factura de Compra',
    labelPlural: 'Facturas de Compra',
    tableName: 'purchaseInvoices',
    schemaTable: schema.purchaseInvoices,
    lineSchemaTable: schema.purchaseInvoiceLines,
    batchSchemaTable: schema.purchaseInvoiceLineBatches,
    eventPrefix: 'purchaseInvoice',
    stockAction: 'IN',
    closeBaseDocuments: true,
    hooks: purchaseInvoiceHooks,
    initialStatus: 'D',
    headerPgName: 'PurchaseInvoice',
    linePgName: 'PurchaseInvoiceLine',
    lineFk: 'invoiceId',
    headerRefKey: 'invoiceId',
    apiPath: '/api/purchases/invoices',
    hasFiscalFields: true,
    hasWarehouse: true,
    hasInternalOrder: false,
    hasSalesAgent: false,
    statusLabels: { O: 'Registrada', C: 'Cerrada', X: 'Cancelada', D: 'Borrador' },
    baseDocType: 'PDN',
    uiRoute: '/purchases/invoices',
    linesCarryBaseRef: true,
  },
  {
    docType: 'SO',
    side: 'sales',
    category: 'order',
    label: 'Pedido de Venta',
    labelPlural: 'Pedidos de Venta',
    tableName: 'salesOrders',
    schemaTable: schema.salesOrders,
    lineSchemaTable: schema.salesOrderLines,
    batchSchemaTable: null,
    eventPrefix: 'salesOrder',
    stockAction: 'NONE',
    closeBaseDocuments: false,
    hooks: salesOrderHooks,
    initialStatus: 'O',
    headerPgName: 'SalesOrder',
    linePgName: 'SalesOrderLine',
    lineFk: 'orderId',
    headerRefKey: 'orderId',
    apiPath: '/api/sales',
    hasFiscalFields: false,
    hasWarehouse: true,
    hasInternalOrder: true,
    hasSalesAgent: false,
    statusLabels: { O: 'Abierto', P: 'Parcial', C: 'Cerrado', X: 'Cancelado' },
    uiRoute: '/sales-orders',
    headerBaseRef: { column: 'quoteId', baseDocType: 'SQ' },
  },
  {
    docType: 'PO',
    side: 'purchase',
    category: 'order',
    label: 'Pedido de Compra',
    labelPlural: 'Pedidos de Compra',
    tableName: 'purchaseOrders',
    schemaTable: schema.purchaseOrders,
    lineSchemaTable: schema.purchaseOrderLines,
    batchSchemaTable: null,
    eventPrefix: 'purchaseOrder',
    stockAction: 'NONE',
    closeBaseDocuments: false,
    initialStatus: 'O',
    headerPgName: 'PurchaseOrder',
    linePgName: 'PurchaseOrderLine',
    lineFk: 'orderId',
    headerRefKey: 'orderId',
    apiPath: '/api/purchases/orders',
    hasFiscalFields: false,
    hasWarehouse: true,
    hasInternalOrder: true,
    hasSalesAgent: false,
    statusLabels: { O: 'Abierto', P: 'Parcial', C: 'Cerrado', X: 'Cancelado' },
    uiRoute: '/purchase-orders',
  },
  {
    docType: 'SDN',
    side: 'sales',
    category: 'delivery_note',
    label: 'Albarán de Venta',
    labelPlural: 'Albaranes de Venta',
    tableName: 'salesDeliveryNotes',
    schemaTable: schema.salesDeliveryNotes,
    lineSchemaTable: schema.salesDeliveryNoteLines,
    batchSchemaTable: schema.salesDeliveryNoteLineBatches,
    eventPrefix: 'salesDeliveryNote',
    stockAction: 'OUT',
    closeBaseDocuments: false,
    hooks: salesDeliveryNoteHooks,
    initialStatus: 'O',
    headerPgName: 'SalesDeliveryNote',
    linePgName: 'SalesDeliveryNoteLine',
    lineFk: 'deliveryId',
    headerRefKey: 'deliveryId',
    apiPath: '/api/sales/delivery-notes',
    hasFiscalFields: false,
    hasWarehouse: true,
    hasInternalOrder: false,
    hasSalesAgent: false,
    statusLabels: { O: 'Abierto', P: 'Parcial', C: 'Cerrado', X: 'Cancelado' },
    uiRoute: '/sales/delivery-notes',
    headerBaseRef: { column: 'orderId', baseDocType: 'SO' },
  },
  {
    docType: 'PDN',
    side: 'purchase',
    category: 'delivery_note',
    label: 'Albarán de Compra',
    labelPlural: 'Albaranes de Compra',
    tableName: 'purchaseDeliveryNotes',
    schemaTable: schema.purchaseDeliveryNotes,
    lineSchemaTable: schema.purchaseDeliveryNoteLines,
    batchSchemaTable: schema.purchaseDeliveryNoteLineBatches,
    eventPrefix: 'purchaseDeliveryNote',
    stockAction: 'IN',
    closeBaseDocuments: false,
    hooks: purchaseDeliveryNoteHooks,
    initialStatus: 'O',
    headerPgName: 'PurchaseDeliveryNote',
    linePgName: 'PurchaseDeliveryNoteLine',
    lineFk: 'deliveryId',
    headerRefKey: 'deliveryId',
    apiPath: '/api/purchases/delivery-notes',
    hasFiscalFields: false,
    hasWarehouse: true,
    hasInternalOrder: false,
    hasSalesAgent: false,
    statusLabels: { O: 'Abierto', P: 'Parcial', C: 'Cerrado', X: 'Cancelado' },
    uiRoute: '/purchases/delivery-notes',
    headerBaseRef: { column: 'orderId', baseDocType: 'PO' },
  },
  {
    docType: 'SQ',
    side: 'sales',
    category: 'quote',
    label: 'Presupuesto',
    labelPlural: 'Presupuestos',
    tableName: 'salesQuotes',
    schemaTable: schema.salesQuotes,
    lineSchemaTable: schema.salesQuoteLines,
    batchSchemaTable: null,
    eventPrefix: 'salesQuote',
    stockAction: 'NONE',
    closeBaseDocuments: false,
    initialStatus: 'O',
    headerPgName: 'SalesQuote',
    linePgName: 'SalesQuoteLine',
    lineFk: 'quoteId',
    headerRefKey: 'quoteId',
    // Sin router Express propio — CRUD 100% vía el router genérico.
    apiPath: '/api/documents/SQ',
    hasFiscalFields: false,
    hasWarehouse: false,
    hasInternalOrder: true,
    hasSalesAgent: true,
    statusLabels: { O: 'Abierto', A: 'Aceptado', R: 'Rechazado', X: 'Cancelado' },
    uiRoute: '/sales/quotes',
    // Aceptar/Rechazar a mano desde la UI (y reabrir si fue un error).
    manualStatusTransitions: { O: ['A', 'R'], A: ['O'], R: ['O'] },
  },
];

/** Deriva kind de la categoría para el meta-registro de @openfactu/common. */
function kindOf(category: string): 'order' | 'deliveryNote' | 'invoice' {
  if (category === 'delivery_note') return 'deliveryNote';
  if (category === 'invoice') return 'invoice';
  return 'order';
}

// Registrar todos al importar — en el DocumentRegistry propio y en el
// meta-registro runtime de @openfactu/common (decomposeDocType, labels...).
for (const config of CONFIGS) {
  DocumentRegistry.register(config);
  registerDocTypeMeta({
    docType: config.docType,
    kind: kindOf(config.category),
    side: config.side === 'sales' ? 'sale' : 'purchase',
    label: config.label,
    labelPlural: config.labelPlural,
    apiEndpoint: config.apiPath,
    route: config.uiRoute,
  });
}

export { CONFIGS };
